/*
 *  Released under the GNU LGPL.  See http://www.gnu.org/licenses/lgpl.txt
 *
 *  This program is part of the DeSmet C Compiler
 *
 *  This library is free software * you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published
 *  by the Free Software Foundatation * either version 2.1 of the License, or
 *  any later version.
 *
 *  This library is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY * without even the implied warranty of MERCHANTABILITY
 *  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 *  License for more details.
 */
#define	IBETA	2
#define	IT		52
#define	IRND	0
#define	NGRD	1
#define	MACHEP	-51
#define	NEGEPS	-51
#define	IEXP	11
#define	MINEXP	-1022
#define	MAXEXP	1026
#define	EPS		4.4408920985006E-16
#define	EPSNEG	4.4408920985006E-16
#define	XMIN	2.2250738585071E-300
#define	XMAX	3.5953862697245E+300
#define	SMALLX	-6.899757E2
#define	BIGX	6.920551E2
