/*
 *  Released under the GNU GPL.  See http://www.gnu.org/licenses/gpl.txt
 *
 *  This program is part of the DeSmet C Compiler
 *
 *  DeSmet C is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundatation; either version 2 of the License, or any
 *  later version.
 *
 *  DeSmet C is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 *  for more details.
 */
			/*  Start of file VERSION.H  */

/*
		 O88 Optimizer for DeSmet (C-Ware) C-Compiler
		 --------------------------------------------

			      Copyright (c) 1986

				      by

			    Key Software Products
		    440 Ninth Avenue, Menlo Park, CA 94025
				(415) 364-9847

			    (All rights reserved)


*/

#define	O88 "O88 Optimizer   V3.06d  (c) Key Software Products, 1986-89\r\n"
#define	OPENO88 "OpenO88 Optimizer v0.8 based on\r\n"
#define	CC  "CC  Driver Pgm  V1.04   (c) Key Software Products, 1988-89\r\n"
#define	OPENCC "OpenCC  Driver Pgm v0.8 based on"

			 /*  End of file VERSION.H  */
